const zhNutritionLabels: Record<string, string> = {
  "% daily intake per serving": "每份每日摄入占比",
  "% rdi": "参考摄入量占比",
  "added sugar": "添加糖",
  "added sugars": "添加糖",
  ash: "灰分",
  calcium: "钙",
  calories: "热量",
  "calories from saturated fat": "饱和脂肪供能",
  carbohydrate: "碳水化合物",
  "carbohydrate - total": "总碳水化合物",
  "carbohydrate total": "总碳水化合物",
  carbohydrates: "碳水化合物",
  "carbohydrates - total": "总碳水化合物",
  "carbohydrates, total": "总碳水化合物",
  cholesterol: "胆固醇",
  "crude fat": "粗脂肪",
  "crude fat (min)": "粗脂肪（最低含量）",
  "crude fibre (max)": "粗纤维（最高含量）",
  "crude fibre (max.)": "粗纤维（最高含量）",
  "crude fiber (max)": "粗纤维（最高含量）",
  "crude fiber (max.)": "粗纤维（最高含量）",
  "crude protein": "粗蛋白质",
  "crude protein (min)": "粗蛋白质（最低含量）",
  "dietary fiber": "膳食纤维",
  "dietary fibre": "膳食纤维",
  "dietary fibre - total": "膳食纤维",
  "dietary fibre total": "膳食纤维",
  energy: "能量",
  "energy (approx)": "能量（约）",
  "energy (kilojoules)": "能量（千焦）",
  fat: "脂肪",
  "fat - saturated": "饱和脂肪",
  "fat - total": "总脂肪",
  "fat - transfat": "反式脂肪",
  "fat (min)": "脂肪（最低含量）",
  "fat (total)": "总脂肪",
  "fat saturated": "饱和脂肪",
  "fat total": "总脂肪",
  "fat, saturated": "饱和脂肪",
  "fat, total": "总脂肪",
  "fibre (max.)": "膳食纤维（最高含量）",
  gluten: "麸质",
  iron: "铁",
  magnesium: "镁",
  "metabolizable energy": "代谢能",
  "metabolizable energy (me)": "代谢能（ME）",
  monounsaturated: "单不饱和脂肪",
  "monounsaturated fat": "单不饱和脂肪",
  nutrient: "营养成分",
  "of which sugars": "其中糖",
  "per 1000g": "每 1000g",
  "per 100g": "每 100g",
  "per 100g / 100ml": "每 100g / 100mL",
  "per 100ml": "每 100mL",
  "per serving": "每份",
  polyunsaturated: "多不饱和脂肪",
  "polyunsaturated fat": "多不饱和脂肪",
  potassium: "钾",
  protein: "蛋白质",
  "protein - total": "总蛋白质",
  "protein total": "总蛋白质",
  "protein, total": "总蛋白质",
  "rdi% per serving": "每份参考摄入量占比",
  salt: "盐",
  saturated: "饱和脂肪",
  sodium: "钠",
  sugar: "糖",
  "sugar - total": "总糖",
  sugars: "总糖",
  "sugars, total": "总糖",
  "total carbohydrate": "总碳水化合物",
  "total fat": "总脂肪",
  "total protein": "总蛋白质",
  "total saturated fatty acids": "饱和脂肪酸总量",
  "total sugars": "总糖",
  trans: "反式脂肪",
  "trans fats": "反式脂肪",
  "-trans": "反式脂肪",
  "-sugars": "糖",
};

function normalizeNutritionLabel(value: string) {
  return value
    .trim()
    .toLocaleLowerCase("en")
    .replace(/[—–]/g, "-")
    .replace(/\s+/g, " ");
}

export function localizeNutritionLabel(
  locale: string,
  originalValue: string | null | undefined,
  translatedValue: string,
) {
  if (locale !== "zh") return translatedValue;

  const lookupValue = originalValue || translatedValue;
  return zhNutritionLabels[normalizeNutritionLabel(lookupValue)] ?? translatedValue;
}
